name: bootstrap_for_pub
description: Just Bootstrap's files, in a pub package.
authors:
- Bootstrap core team
version: 3.2.0
homepage: https://github.com/sethladd/bootstrap_for_pub
dependencies:
  barback: ">=0.14.1+3 <0.15.0"
  html5lib: ">=0.11.0+1 <0.12.0"