name: bootstrap_for_pub
description: Just Bootstrap's files, in a pub package.
authors:
- Bootstrap core team
- Seth Ladd <sethladd@gmail.com>
version: 3.1.0
homepage: https://github.com/sethladd/bootstrap_for_pub
